### ISSUE TITLE
Code eligible for RENAC inverters

### ISSUE THREAD

**Issue by windmillBart** [paolosabatino/saj-mqtt#5]
Hi,
I have a RENAC Hybrid inverter with a DIY Battery with Daly BMS.
Both are connected with a linux server via USB Adapters RS485 -> wifi RX-TX and USB Adapter TTL -> Daly BMS
with Home assistant I use the modbus integration to read the registers from the inverter. (I have used modbustest to map the registers because i can't find any OEM documentation so far)

I tried to use home assistant to write to the registers to control the work mode of the inverter but with no success.
would I be able to use your code to write to the registers? I have been trying to write some code myself in python and the read function 0x03 works well but the write 0x06 or 0x10 always gives me an error like value not allowed.

anything I need to consider before starting to change your code (to match the RENAC registers) ?

Bart

**Comment by paolosabatino** [comment]
Hello, 
I know nothing about RENAC inverters, this repository is for SAJ inverters which use their own MQTT broker communication protocolo to read and write registers. If your inverter is not a rebadged SAJ inverter which use the same protocol, I doubt it would be useful.

Anyway, I have no problems in integrate future possible support for other inverters, but this is a question rather than a real issue about the project, so I close this.
